#Spring configuration file
spring:
  application:
    name: mobilemanagement
  profiles:
    active: ${PROFILE:prod} #Switch to dev for local development
management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db"
        liveness:
          include: livenessState
