#Spring configuration for production
spring:
  config:
    import: "sm://"
  cloud:
    gcp:
      secretmanager:
        enabled: true
  datasource:
    url: jdbc:mysql://${sm@projects/356074917522/secrets/MYSQL_HOST/versions/latest}:${sm@projects/356074917522/secrets/MYSQL_PORT/versions/latest}/${sm@projects/356074917522/secrets/MYSQL_DATABASE/versions/latest}
    username: ${sm@projects/356074917522/secrets/MYSQL_USER/versions/latest}
    password: ${sm@projects/356074917522/secrets/MYSQL_PASSWORD/versions/latest}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false