apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        componentType: DB
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_ONETIME_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "mobilemanagement"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
            - name: mysql-secret-vol
              mountPath: /etc/mysql-secrets
              readOnly: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysql -u $(cat /etc/mysql-secrets/username) -p$(cat /etc/mysql-secrets/password) -e 'SELECT 1;'"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysql -u $(cat /etc/mysql-secrets/username) -p$(cat /etc/mysql-secrets/password) -e 'SELECT 1;'"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-claim
        - name: mysql-secret-vol
          secret:
            secretName: mysql-secret
